package com.infy.statics;

public class TestAutoGeneratedID {

	public static void main(String[] args) {
		Employee e1=new Employee("Ratna",10);
		e1.displayDetails();
		
		Employee e2=new Employee("Pinakin",16);
		e2.displayDetails();
		
		Employee e3=new Employee("Uttam",18);
		e3.displayDetails();
	}

}
